using System.Text.Json;
using System.Text.Json.Serialization;

namespace Forge.Core.Manifest;

/// <summary>The one document every surface reads. Generated by tools/build_manifest.py; never edited by hand.</summary>
public sealed class Manifest
{
    [JsonPropertyName("schemaVersion")] public int SchemaVersion { get; set; }
    [JsonPropertyName("generatedAt")] public string GeneratedAt { get; set; } = "";
    [JsonPropertyName("releases")] public string Releases { get; set; } = "";
    [JsonPropertyName("channels")] public List<string> Channels { get; set; } = [];
    [JsonPropertyName("sets")] public List<SetInfo> Sets { get; set; } = [];
    [JsonPropertyName("plugins")] public List<PluginInfo> Plugins { get; set; } = [];

    public PluginInfo? Plugin(string id) =>
        Plugins.FirstOrDefault(p => string.Equals(p.Id, id, StringComparison.OrdinalIgnoreCase));

    public SetInfo? Set(string id) =>
        Sets.FirstOrDefault(s => string.Equals(s.Id, id, StringComparison.OrdinalIgnoreCase)
                              || string.Equals(s.Name, id, StringComparison.OrdinalIgnoreCase));

    /// <summary>The editor plugin that ships with every engine install: the menu, the update badge, the Fab bridge.</summary>
    public const string HubPlugin = "AutomationForgeHub";

    /// <summary>
    /// An engine install always carries the editor plugin, first, when the
    /// manifest knows it. A project install does not: the project's owner
    /// decides what goes into the project.
    /// </summary>
    public IReadOnlyList<string> WithHubPlugin(IEnumerable<string> ids, string targetKind)
    {
        var list = ids.ToList();
        if (targetKind == "engine" && Plugin(HubPlugin) is not null && !list.Contains(HubPlugin, StringComparer.OrdinalIgnoreCase))
            list.Insert(0, HubPlugin);
        return list;
    }

    /// <summary>The plugin plus everything it depends on, dependencies first, no duplicates.</summary>
    public IReadOnlyList<PluginInfo> Closure(PluginInfo plugin)
    {
        var order = new List<PluginInfo>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        void Walk(PluginInfo p)
        {
            if (!seen.Add(p.Id)) return;
            foreach (var dep in p.Dependencies)
                if (Plugin(dep) is { } d) Walk(d);
            order.Add(p);
        }
        Walk(plugin);
        return order;
    }
}

public sealed class SetInfo
{
    [JsonPropertyName("id")] public string Id { get; set; } = "";
    [JsonPropertyName("name")] public string Name { get; set; } = "";
    [JsonPropertyName("members")] public List<string> Members { get; set; } = [];
}

public sealed class PluginInfo
{
    [JsonPropertyName("id")] public string Id { get; set; } = "";
    [JsonPropertyName("set")] public string Set { get; set; } = "";
    [JsonPropertyName("role")] public string Role { get; set; } = "";
    /// <summary>open · fab · paid</summary>
    [JsonPropertyName("distribution")] public string Distribution { get; set; } = "";
    [JsonPropertyName("dependencies")] public List<string> Dependencies { get; set; } = [];
    [JsonPropertyName("source")] public string? Source { get; set; }
    [JsonPropertyName("versions")] public List<VersionInfo> Versions { get; set; } = [];

    public bool IsPaid => Distribution == "paid";

    /// <summary>
    /// Newest version for an engine on a channel, or null when none is published.
    /// The stable channel sees stable releases only; the nightly channel sees
    /// whichever is newest of both, so a stable release published after a
    /// nightly supersedes it.
    /// </summary>
    public VersionInfo? Latest(string engine, string channel = Settings.Stable) =>
        Versions.Where(v => v.Engine == engine && (channel == Settings.Nightly || v.Channel == Settings.Stable))
                .OrderByDescending(v => v.ReleasedAt, StringComparer.Ordinal)
                .FirstOrDefault();
}

public sealed class VersionInfo
{
    [JsonPropertyName("version")] public string Version { get; set; } = "";
    [JsonPropertyName("engine")] public string Engine { get; set; } = "";
    [JsonPropertyName("platform")] public string Platform { get; set; } = "";
    [JsonPropertyName("channel")] public string Channel { get; set; } = "stable";
    /// <summary>Null for a paid plugin: the download URL is issued per request, after the entitlement check.</summary>
    [JsonPropertyName("url")] public string? Url { get; set; }
    [JsonPropertyName("size")] public long Size { get; set; }
    [JsonPropertyName("sha256")] public string? Sha256 { get; set; }
    [JsonPropertyName("symbols")] public string? Symbols { get; set; }
    [JsonPropertyName("releasedAt")] public string ReleasedAt { get; set; } = "";
    [JsonPropertyName("notes")] public string? Notes { get; set; }
}

/// <summary>Fetches the manifest, keeps the last good copy, and serves it offline.</summary>
public sealed class ManifestClient
{
    public const string DefaultUrl = "https://raw.githubusercontent.com/AutomationForgeHQ/automation-forge/main/manifest.json";

    private static readonly JsonSerializerOptions Json = new() { PropertyNameCaseInsensitive = true };
    private readonly HttpClient _http;
    private readonly string _cachePath;

    public string Url { get; }

    public ManifestClient(HttpClient http, string? url = null, string? cacheDir = null)
    {
        _http = http;
        Url = url ?? Environment.GetEnvironmentVariable("FORGE_MANIFEST_URL") ?? DefaultUrl;
        _cachePath = Path.Combine(cacheDir ?? Paths.DataDir, "manifest.json");
    }

    /// <summary>Fresh from the network when possible; the cached copy otherwise. Throws only when there is neither.</summary>
    public async Task<(Manifest manifest, bool fromCache)> GetAsync(bool offline = false, CancellationToken ct = default)
    {
        if (!offline)
        {
            try
            {
                using var resp = await _http.GetAsync(Url, ct);
                resp.EnsureSuccessStatusCode();
                var text = await resp.Content.ReadAsStringAsync(ct);
                var fresh = JsonSerializer.Deserialize<Manifest>(text, Json) ?? throw new InvalidDataException("Empty manifest.");
                Directory.CreateDirectory(Path.GetDirectoryName(_cachePath)!);
                await File.WriteAllTextAsync(_cachePath, text, ct);
                return (fresh, false);
            }
            catch (Exception) when (File.Exists(_cachePath))
            {
                // Fall through to the cache: the network is optional, the manifest is not.
            }
        }
        if (!File.Exists(_cachePath))
            throw new InvalidOperationException($"No manifest available: could not reach {Url} and there is no cached copy.");
        var cached = JsonSerializer.Deserialize<Manifest>(await File.ReadAllTextAsync(_cachePath, ct), Json)
                     ?? throw new InvalidDataException("Cached manifest is unreadable.");
        return (cached, true);
    }
}
